// web/components/playground/stats/Stats.jsx


import PocketBase from 'pocketbase'
import { useEffect, useState } from 'react'

export default function Stats({ data }){
    
    const BlockGeneral = ({ one, two, three }) => {
        return(
            <div className="stats shadow">
                <div className="stat">
                    <div className="stat-title">Size</div>
                    <div className="stat-value">{one}</div>
                </div>
                
                <div className="stat">
                    <div className="stat-title">Longest Path</div>
                    <div className="stat-value">{two}</div>
                </div>
                
                <div className="stat">
                    <div className="stat-title">Shortest Path</div>
                    <div className="stat-value">{three}</div>
                </div>
            </div>
        )
    }

    const Block = ({ one, two, three }) => {
        return(
            <div className="stats shadow">
                <div className="stat">
                    <div className="stat-title">ID</div>
                    <div className="stat-value">{one}</div>
                </div>
                
                <div className="stat">
                    <div className="stat-title">Path Length</div>
                    <div className="stat-value">{two}</div>
                </div>
                
                <div className="stat">
                    <div className="stat-title">Time To Solve</div>
                    <div className="stat-value">{three}</div>
                </div>
            </div>
        )
    }

    const save = () => {

        console.log(data)

        const createData = {
            "search": data,
        }

        // console.log(createData)

        const fetchData = async () => {
            const pb = new PocketBase('http://localhost:8090')
            const authData = await pb.admins.authWithPassword('shelleywr23@mail.vmi.edu', 'rootrootroot');
            const record = await pb.collection('searchRecords').create(createData);
        }
        fetchData()
    }

    return(
        <div className="grid justify-center">
            <div className="flex justify-center ">
                <div className="">
                    <h1 className="text-center text-4xl p-10">Overview</h1>
                </div>
                <div className=" flex items-center justify-center">
                    <button className="btn" onClick={save}>Save</button>
                </div>
            </div>
            <BlockGeneral one={data.stats.size} two={data.stats.longestPath} three={data.stats.shortestPath}/>

            <h1 className="text-center text-4xl p-10">Agents</h1>
            <div className="grid grid-cols-1 gap-5">
                {data.agents.map((agent, index) => {
                    return(
                        <Block key={index} one={agent.stats.id} two={agent.stats.path} three={agent.stats.time}/>
                    )
                })}
            </div>
        </div>
    )
}

// frontend/src/lib/main/Stats.svelte
<script>

$: to_be_fetched = {
        grid: [
            ["c", "c", "c", "c", "c"],
            ["a-d", "a-d", "a-d", "c", "c"],
            ["c", "c", "c", "c", "c"],
            ["c", "c", "c", "g", "c"],
            ["c", "c", "c", "c", "c"]
        ],
        stats: {
            size: 5,
            longestPath: 7,
            shortestPath: 5,
        },
        agents: [
            {
                position: {
                    x: 0,
                    y: 1,
                },
                status: "a-d",
                sequence: ['l', 'r  ', 'm', 'm', 'l', 'm', 'm'],
                stats: {
                    id: 1,
                    time: 5,
                    path: 5,
                }
            },
        ], 
        searchTypes: [
            "Breadth First Search",
            "Depth First Search",
            "Depth Limit Search",
            "Uniform Cost Search",
            "Iterative Depth Limited Search"
        ]
    }

</script>

<div class="flex justify-center">
    <div class="p-3 w-[40em] bg-white grid">
        <h1 class="text-3xl bold p-5 text-center">Stats</h1>
        <div class="grid gap-5">
            <div class="stats shadow">
                <div class="stat">
                    <div class="stat-title">Longest Path</div>
                    <div class="stat-value text-primary">25.6K</div>
                </div>
    
                <div class="stat">
                    <div class="stat-title">Shortest Path</div>
                    <div class="stat-value text-primary">25.6K</div>
                </div>
    
                <div class="stat">
                    <div class="stat-title">Longest Time</div>
                    <div class="stat-value text-primary">25.6K</div>
                </div>
            </div>
        </div>
    
        <h1 class="text-center p-5 text-3xl">Individual Trucks</h1>
        <div class="grid gap-5">
            {#each to_be_fetched.agents as agent}
    
            <div class="stats shadow">
                <div class="stat">
                    <div class="stat-title">Truck ID</div>
                    <div class="stat-value text-primary">Truck {agent.stats.id}</div>
                </div>
                
                <div class="stat">
                    <div class="stat-title">Path Length</div>
                    <div class="stat-value text-primary">{agent.stats.path}</div>
                </div>
    
                <div class="stat">
                    <div class="stat-title">Time to solve</div>
                    <div class="stat-value text-primary">{agent.stats.time}s</div>
                </div>
            </div>
            {/each}
        </div>  
    </div>
</div>
